### ISSUE TITLE
Password reset form visually defect

### ISSUE THREAD

**Issue by pitpalme** [volunteer-planner/volunteer_planner#97] opened 2015-09-19 07:50 UTC
If you want/need to reset your password the form looks like it's not accepting any values.
You don't see you've entered text into the password fields, unless you "select" the fields content.
The "Set password" button looks like being disabled.

![image](https://cloud.githubusercontent.com/assets/748801/9975206/c89bf00c-5eb3-11e5-8d9d-0fdb5898217d.png)

Users (maybe not all, but at least some) assume the form is not working, this should be fixed to reflect a reasonable UX.

**Comment by tordans** [comment] 2015-09-19 08:21
I noticed this too, its annoying and nearly prevented me from signing up.

**Comment by tordans** [comment] 2015-09-19 13:10
The issue is a combination of bootstrap together with some very rough css-overwrites that you use in the application. There is a (text) color on the body element which sets the color to white. Bootstrap then goes and tells all forms to "inherit" the color, which is now white. 

I think the cleanest way to solve this is to regenerate a new bootstrap css and this time use the customization options right inside the generator at http://getbootstrap.com/customize/. One can set the text-color to white there, which should not affect the inputs.

Will will commit some form cleanups today but since I dont have a running dev env I will need help with someone who tests and adjusts it if needed.

**Comment by christophmeissner** [comment] 2015-09-21 17:12
Fixed by #101

**Closed by christophmeissner** 2015-09-21 17:12 UTC
Labels: bug
